/**
 * BU Smart App API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 *
 * @param createdAtUtc
 * @param lastUpdatedAtUtc
 * @param createdBy
 * @param lastUpdatedBy
 * @param isDeleted
 */
data class TrackAbleEntity(

    val id: String? = null,
    val createdAtUtc: String? = null,
    val lastUpdatedAtUtc: String? = null,
    val createdBy: String? = null,
    val lastUpdatedBy: String? = null,
    val isDeleted: Boolean? = null
)

data class Shop(
    val id: String? = null,
    val name: String? = null,
    val type: ShopType
)

enum class ShopType {
    Cafe,
    Stationary
}

data class ShopItem(
    val id: String? = null,
    val createdAtUtc: String? = null,
    val lastUpdatedAtUtc: String? = null,
    val createdBy: String? = null,
    val lastUpdatedBy: String? = null,
    val isDeleted: Boolean? = null,
    val name: String? = null,
    val price: Int? = 0,
    val shopId: String
)

data class Order(
    val id: String? = null,
    val createdAtUtc: String? = null,
    val lastUpdatedAtUtc: String? = null,
    val createdBy: String? = null,
    val lastUpdatedBy: String? = null,
    val isDeleted: Boolean? = null,
    val isActive: Boolean = true,
    val shopId: String,
    val orderItems: List<OrderItem>? = null
)

data class OrderItem(
    val id: String? = null,
    val orderId: String? = null,
    val itemId: String? = null,
    val quantity: Int? = 0
)


data class ShopVm(
    val id: String? = null,
    val name: String? = null,
    val type: Int? = 0,
    val imgResource: Int = 0
)

data class ShopItemVm(
    val id: String? = null,
    val shopId: String? = null,
    val name: String? = null,
    val price: Int? = 0
)

data class OrderVm(
    val id: String? = null,
    val shopName: String? = null,
    val isActive: Boolean = true,
    val orderItems: List<OrderItemVm>? = null
)

data class OrderItemVm(
    val id: String? = null,
    val orderId: String? = null,
    val itemName: String? = null,
    val price: Int? = 0,
    val quantity: Int? = 0
)